language: java
jdk: openjdk8

services:
  - docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t lukefox/dive-rest-service ./diveService
  - docker push lukefox/dive-rest-service