language: java
jdk: openjdk8

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - docker build -t lukefox/dive-rest-service ./diveService
  - docker tag lukefox/dive-rest-service lukefox/dive-rest-service:$TAG
  - docker push lukefox/dive-rest-service

  - docker build -t lukefox/registry ./eureka-service
  - docker tag lukefox/registry lukefox/registry:$TAG
  - docker push lukefox/registry

  - docker build -t lukefox/gateway-service ./zuul-gateway-service
  - docker tag lukefox/gateway-service lukefox/gateway-service:$TAG
  - docker push lukefox/gateway-service
